### ISSUE TITLE
Allow hovering over elements and showing their reference designator

### ISSUE THREAD

**Issue by seveibar** [tscircuit/3d-viewer#30]
If i hover over a component, I'd like something to show me what it's reference designator is. We should also highlight the component to indicate it's being hovered over.

![Image](https://github.com/user-attachments/assets/f23982a5-7dae-4982-b29b-544dfab34a39)

**Comment by ShiboSoftwareDev** [comment]
![Image](https://github.com/user-attachments/assets/d462028d-4b9d-4bc2-8dc7-7bcd2610cff0)
@seveibar initial implementation, what do you think?

**Comment by seveibar** [comment]
Design is good! Minor nit: just throw font family sans-serif on it for slightly better aesthetic

**Comment by ShiboSoftwareDev** [comment]
closed in #33
