### ISSUE TITLE
plated hole pill shape only allows width to be bigger than height

### ISSUE THREAD

**Issue by ShiboSoftwareDev** [tscircuit/3d-viewer#43]
it should allow height to be bigger than width and drow a 90 degree rotated pill shape without erroring

**Comment by ShiboSoftwareDev** [comment]
@seveibar this is what is making 3d-viewer crash in snippets

**Comment by seveibar** [comment]
oof ok good to know and makes sense

**Comment by ShiboSoftwareDev** [comment]
/attempt #43 I'm working on a fix
